### ISSUE TITLE
AxMines - Unable to load updated configs.

### ISSUE THREAD

**Issue by penkDev** [Artillex-Studios/Issues#122]
### Description of the bug

https://paste.artillex-studios.com/8M5fscJ

It looks like the plugin isnt able to load the config files. I noticed that after updating the messages.yml

Mines by it self seem to work completely fine even tho the plugin is reporting that the configuration cannot be loaded. But the messages.yml dont seem to update and keep using the original version.
Here is the config file of messages YML
```
messages:
  prefix: '<#00AAFF><b>AxMines</b> <gray>»</gray> '
  reload: Reloaded in <time> ms!
  reset: Mine <mine> was automatically reset!
  selection:
    pos1: '<white>Selected <#FF6600>POSITION #1 <gray>- <#DDDDDD><location>'
    pos2: '<white>Selected <#FF6600>POSITION #2 <gray>- <#DDDDDD><location>'
  already-exists: <#ff0000>A mine with name <mine> already exists!
  doesnt-exist: <#ff0000>That mine doesn't exist!
  no-selection: <#ff0000>You haven't made a selection, or it isn't complete!
  actionbar: <f>Reset za: <#88ff00><time>
  time:
    second: s
    minute: m
    hour: h
    day: d
  list:
  - ' '
  - <#00AAFF><b>AxMines</b> <gray>»</gray>
  - ' <gray>- <white>Current mines: <mines>'
  - ' '
  help:
  - ' '
  - <#00AAFF><b>AxMines</b> <gray>»</gray>
  - ' <gray>- <white>/axmines reload <gray>| <#00AAFF>Reload the config'
  - ' <gray>- <white>/axmines wand <gray>| <#00AAFF>Get a mine selection wand'
  - ' <gray>- <white>/axmines delete <gray>| <#00AAFF>Delete a mine'
  - ' <gray>- <white>/axmines list <gray>| <#00AAFF>List all mines'
  - ' <gray>- <white>/axmines redefine <gray>| <#00AAFF>Redefine a mine'
  - ' <gray>- <white>/axmines teleport <gray>| <#00AAFF>Teleport to a mine'
  - ' <gray>- <white>/axmines editor <gray>| <#00AAFF>Open the mine editor'
  - ' <gray>- <white>/axmines setteleport <gray>| <#00AAFF>Set the teleport location of a mine'
  - ' <gray>- <white>/axmines create <gray>| <#00AAFF>Create a mine'
  - ' <gray>- <white>/axmines reset <gray>| <#00AAFF>Reset a mine'
  - ''
  redefine: <color:#00FF00>Successfully redefined!
  teleport: <color:#00FF00>Teleporting!
  set-teleport: <color:#00FF00>You've set the teleport to your location!

```

Here is a config of a mine
```
display-name: <color:#FF0000>jungleplanksjung2</#FF0000>

contents:
  jungle_planks: 10

selection:
  '1': arena3;-126.0;77.0;156.0;0.0;0.0
  '2': arena3;-117.0;84.0;147.0;0.0;0.0

teleport-location: arena3;-117.0;84.0;147.0;0.0;0.0

# To top block at player's location: 0
# To teleport to teleport-location: 1
# To disable, set to anything else
teleport-on-reset: 0

actionbar:
  enabled: true
  range: 10

# For broadcast in range: >= 1
# For whole world: 0
# For all worlds: -1
# For silent mode: -2
broadcast-reset: -2

# How often the mine should reset
# 20 ticks = 1 second
reset:
  # (10 minutes)
  ticks: 600
  # At what percent the mine should automagically
  # reset set to 0 to disable
  percent: -1.0

# If you want it to work on any block, leave it empty, or don't even add it
# Item reward
# Command reward
random-rewards:
- chance: 0.001
  blocks:
  - diamond_block
  - emerald_block
  items:
  - type: stone
    name: oreo
  commands:
  - eco give <player> 100000

# The commands to run when the mine is reset
reset-commands: []
#The format of the time placeholder
#1 -> HH:MM:SS, for example 01:25:35
#2 -> short format, for example 20m
#3 - text format, for example 01h 25m 35s
timer-format: 2
#What blocksetter should we use to set the blocks?
#Options:
#parallel - Best performance, does not lag the server thread. Sometimes can be a little bit inaccurate
#fast - Sets the blocks on the main thread using faster methods
#bukkit - Uses the Bukkit API to set the blocks. This is the slowest out of all the setters
#
#If you are having issues with blocks not being set correctly, we suggest using bukkit.
setter: parallel

```

### Expected behaviour

Config files should be able to be loaded correctly.

### Steps to reproduce

Use version from spigot. https://www.spigotmc.org/resources/axmines-the-ultimate-mines-plugin.115845/ (1.3.0)
Further no idea why that would be happening.

### Which plugin is this issue with?

axmines

### Versions

1.3.0
