### ISSUE TITLE
[FEATURE] AH History Button

### ISSUE THREAD

**Issue by burnplayz** [Artillex-Studios/Issues#15]
### Description of the feature

AH History item in /ah

### In which plugin would you like this feature?

axauctions

### Agreements

- [X] I have checked that this feature does not exist in the current latest version of the plugin available.
- [X] I accept that my feature request might not be added, and might be refused without any apparent reason.

**Comment by BenceX100** [comment]
Since the gui rewrite you can do something like this:

```
history:
  slot: 40
  material: "PAPER"
  name: "&#00DDFF&lHistory"
  lore:
    - " "
    - " &fClick here to go"
    - " &fto the history page!"
    - " "
    - "&#00DDFF&lClick &#DDDDDD» &#AAFFFFHistory Page"
  actions:
    - "[MENU] history"
    - "[SOUND] ui.button.click|1|1"
```
