### ISSUE TITLE
[AxTrade] Incorrectly Parsed Placeholder in Trade Menu

### ISSUE THREAD

**Issue by Litning11** [Artillex-Studios/Issues#175]
### Description of the bug

The %player% placeholder does not get parsed properly in certain sections of the trade GUI. 

### Expected behaviour

The player other player's username (the one being traded with) should display. 

### Steps to reproduce

In the gui.yml file under the partner section:

```
  currency1:
    slot: 6
    currency: Vault
    material: GOLD_NUGGET
    name: '&6&lGold'
    lore:
    - '&7&l%player% offers'
    - '&c&m&l---------------'
    - '&7Amount: &6&l%amount%G'
    - '&c&m&l---------------'
    - '&7&l> &c&lChange Amount'
  currency2:
    slot: 5
    currency: Experience
    material: EXPERIENCE_BOTTLE
    name: '&b&lExperience'
    lore:
    - '&7&l%player% offers'
    - '&c&m&l---------------'
    - '&7Amount: &b&l%amount% EXP'
    - '&c&m&l---------------'
    - '&7&l> &c&lChange Amount'
```

### Which plugin is this issue with?

axtrade

### Versions

Current Purpur Version: 1.21.4-2412-9249a2c (MC: 1.21.4)
AxTrade version 1.16.1
