### ISSUE TITLE
[AxLobby] Incorrect %player% Parsing

### ISSUE THREAD

**Issue by dxnnv** [Artillex-Studios/Issues#202]
### Description of the bug

%player% placeholder is not being parsed correctly in `join-leave-messages.yml`.

Snippet of `join-leave-messages.yml` containing the issue:
```yaml
# set to false to disable the module
enabled: true

# the message will be sent to the player right after they join
message-of-the-day:
  enabled: true
  # delay to send the message
  # in ticks
  # 20 ticks = 1 second
  delay-ticks: 10
  message:
  - " "
  - '<#bcc3cf>ᴡᴇʟᴄᴏᴍᴇ <#66D6E1><font:small>%player%</font>
```

### Expected behaviour

The %player% placeholder should resolve to the player that triggered the event by joining.

### Steps to reproduce

1. Install AxLobby
2. Create a MOTD in `join-leave-messages.yml`
3. Join a few times, along with a different player joining in between.

[Outcome](https://dxnny.dev/imgs/qd4mizhnWjDeW32H.png)

### Which plugin is this issue with?

axafkzone

### Versions

Pufferfish version 1.21.3-27-HEAD@04bc249 (2024-12-04T01:51:20Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)

AxLobby v1.0.0
