### ISSUE TITLE
[BUG] AxBooster using jobs & advanced enchantment experience boost

### ISSUE THREAD

**Issue by Truongvv10** [Artillex-Studios/Issues#66]
### Issue
When using advanced enchantment veinminer, you will get a lot more experience on jobs like 100x more while having booster active. The booster was configured to give 150% so it should be 2.5x times. 

When mining without veinminer, it works perfectly. 

### Custom enchant
```yml
veinminer:
  display: "%group-color%Vein Miner"
  description: |-
    Ability to mine an entire
    vein of ores.

    §8→ {#b7afa3}Cooldown:
          §f§b{#b7afa3}Base level: %group-color%20s
          §f§b{#b7afa3}Max level: %group-color%2.5s
  applies-to: Pickaxes
  group: MYTHIC
  type: MINING
  applies:
    - ALL_PICKAXE
  levels:
    "1":
      cooldown: 0
      settings:
        whitelist:
          - "COAL_ORE"
          - "COPPER_ORE"
          - "IRON_ORE"
          - "GOLD_ORE"
          - "LAPIS_ORE"
          - "REDSTONE_ORE"
          - "DIAMOND_ORE"
          - "EMERALD_ORE"
          - "NETHER_QUARTZ_ORE"
          - "NETHER_GOLD_ORE"
          - "ANCIENT_DEBRIS"
          - "DEEPSLATE_COAL_ORE"
          - "DEEPSLATE_COPPER_ORE"
          - "DEEPSLATE_IRON_ORE"
          - "DEEPSLATE_GOLD_ORE"
          - "DEEPSLATE_LAPIS_ORE"
          - "DEEPSLATE_REDSTONE_ORE"
          - "DEEPSLATE_DIAMOND_ORE"
          - "DEEPSLATE_EMERALD_ORE"
      effects:
        - BREAK_BLOCK @Veinmine
```

### Booster
```yml
display-name: '%multiplier% &aJobs xp booster'

# the icon shown in guis
icon:
  type: COOKIE

# which plugins should this booster affect?
# list of supported plugins: https://docs.artillex-studios.com/axboosters-supported-plugins.html#booster-hooks
boosted:
- jobsreborn:experience

bossbar:
  # set to false to disable
  enabled: true
  name:
    # server booster
    server: '&f%display_name% &8(&f%time_formatted%&8) (&fServer&8)'
    # player booster
    player: '&f%display_name% &8(&f%time_formatted%&8) (&f%player%&8)'
  color: green
  style: notched_6

# used when a player starts a booster
player-booster:
  start:
  - ' <gradient:#e83b3b:#ffa214:#ffc825:#91db69:#f04f78:#a884f3:#a884f3>┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅</gradient>'
  - ' <#ffc825>%player% <#B7AFA3>has started a <#ffc825>%display_name%'
  - ' <#91db69>Duration: <#B7AFA3>Last for %time_formatted%m'
  - ' <#a884f3>Clickable: <#B7AFA3>&nClick here to thank them!'
  - ' <gradient:#e83b3b:#ffa214:#ffc825:#91db69:#f04f78:#a884f3:#a884f3>┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅</gradient>'
  end:
  - '&e%player%''s &#FFDD00&l%display_name% &ehas now ended!'

# used when the server starts a booster
server-booster:
  start:
  - ' <gradient:#e83b3b:#ffa214:#ffc825:#91db69:#f04f78:#a884f3:#a884f3>┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅</gradient>'
  - ' <#ffc825>Server <#B7AFA3>has started a <#ffc825>%display_name%'
  - ' <#91db69>Duration: <#B7AFA3>Last for %time_formatted%m'
  - ' <#a884f3>Clickable: <#B7AFA3>&nClick here to thank them!'
  - ' <gradient:#e83b3b:#ffa214:#ffc825:#91db69:#f04f78:#a884f3:#a884f3>┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅</gradient>'
  end:
  - '&eServers &#FFDD00&l%display_name% &ehas now ended!'

starter:
  enabled: true
  material: COOKIE
  glow: true
  name: "&8 ● &#a884f3Jobs exp booster"
  lore:
    - "&8 &8&nBooster to be activated"
    - " "
    - '&#DFDFDF This booster is currently'
    - '&#DFDFDF &#a884f3unused &#DFDFDF& can be activated. '
    - ' '
    - '&#DFDFDF Audience: &#a884f3%audience%'
    - '&#DFDFDF Multiplier: &#a884f3%multiplier%'
    - '&#DFDFDF Length: &#a884f3%length%'
    - ' '
    - '&8 (&#a884f3!&8) &#DFDFDFClick to activate booster'

# if you want to override the format section in the guis, you can do it here!
override-lore:
  my-boosters: []
  admin-viewer: []
  active-boosters: []

```

### Screenshot

![Image](https://github.com/user-attachments/assets/f3762520-965e-4f7b-998f-499a9c2b21bd)

### Expected behaviour

It should just act normally with veinminer. 

### Steps to reproduce

I've put the config in the issue if veinminer, use that on a vein of diamond ores with jobs on server then you can see you level up super fast like that screenshot.

### Which plugin is this issue with?

axboosters

### Versions

AxBoosters version 3.6.5 on 1.21.4
