### ISSUE TITLE
AxVaults PlayerHeads texture not show

### ISSUE THREAD

**Issue by PanHaskins** [Artillex-Studios/Issues#77]
Server Version: 1.21.4
Jar type: PAPER
what´s wrong with this config? Or it´s bug? (AxVaults) I need use heads in menu but they haven´t texture:

```yaml
gui-items:
  close:
    material: BARRIER
    name: '&#FF3333&lClose'
  back:
    material: PLAYER_HEAD
    texture: 'base64-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzdhZWU5YTc1YmYwZGY3ODk3MTgzMDE1Y2NhMGIyYTdkNzU1YzYzMzg4ZmYwMTc1MmQ1ZjQ0MTlmYzY0NSJ9fX0='
    name: ' &#FF4848(←) Back '
  previous-page:
    material: PLAYER_HEAD
    texture: 'base64-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzdhZWU5YTc1YmYwZGY3ODk3MTgzMDE1Y2NhMGIyYTdkNzU1YzYzMzg4ZmYwMTc1MmQ1ZjQ0MTlmYzY0NSJ9fX0='
    name: ' &#FF4848(←) Back '
  next-page:
    material: PLAYER_HEAD
    texture: 'base64-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjgyYWQxYjljYjRkZDIxMjU5YzBkNzVhYTMxNWZmMzg5YzNjZWY3NTJiZTM5NDkzMzgxNjRiYWM4NGE5NmUifX19'
    name: ' &#AAFC5C(→) Next Page '
```
