### ISSUE TITLE
[BUG] AxBooster jobs money does not work

### ISSUE THREAD

**Issue by Truongvv10** [Artillex-Studios/Issues#99]
### Description of the bug

Jobs money booster doesnt work! using version `3.7.2`.

```yml
display-name: '%multiplier% &aJobs money booster'

# the icon shown in guis
icon:
  type: GOLDEN_CARROT

# which plugins should this booster affect?
# list of supported plugins: https://docs.artillex-studios.com/axboosters-supported-plugins.html#booster-hooks
boosted:
- jobsreborn:money

bossbar:
  # set to false to disable
  enabled: true
  name:
    # server booster
    server: '&f%display_name% &8(&f%time_formatted%&8) (&fServer&8)'
    # player booster
    player: '&f%display_name% &8(&f%time_formatted%&8) (&f%player%&8)'
  color: green
  style: notched_6

# used when a player starts a booster
player-booster:
  start:
  - ' <gradient:#e83b3b:#ffa214:#ffc825:#91db69:#f04f78:#a884f3:#a884f3>┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅</gradient>'
  - ' <#ffc825>%player% <#B7AFA3>has started a <#ffc825>%display_name%'
  - ' <#91db69>Duration: <#B7AFA3>Last for %time_formatted%m'
  - ' <#a884f3>Clickable: <#B7AFA3>&nClick here to thank them!'
  - ' <gradient:#e83b3b:#ffa214:#ffc825:#91db69:#f04f78:#a884f3:#a884f3>┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅</gradient>'
  end:
  - '&e%player%''s &#FFDD00&l%display_name% &ehas now ended!'

# used when the server starts a booster
server-booster:
  start:
  - ' <gradient:#e83b3b:#ffa214:#ffc825:#91db69:#f04f78:#a884f3:#a884f3>┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅</gradient>'
  - ' <#ffc825>Server <#B7AFA3>has started a <#ffc825>%display_name%'
  - ' <#91db69>Duration: <#B7AFA3>Last for %time_formatted%m'
  - ' <#a884f3>Clickable: <#B7AFA3>&nClick here to thank them!'
  - ' <gradient:#e83b3b:#ffa214:#ffc825:#91db69:#f04f78:#a884f3:#a884f3>┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅</gradient>'
  end:
  - '&eServers &#FFDD00&l%display_name% &ehas now ended!'

starter:
  enabled: true
  material: GOLDEN_CARROT
  glow: true
  name: "<gradient:#FF9A29:#FFCF00><bold>Money Booster</bold></gradient>"
  lore:
    - '&#b7afa3This booster is currently not'
    - '&#b7afa3in use and can be activated. '
    - ' '
    - '&fInformation:'
    - '&8● &#b7afa3Type: <gradient:#FF9A29:#FFCF00>Jobs</gradient>'
    - '&8● &#b7afa3Audience: <gradient:#FF9A29:#FFCF00>%audience%</gradient>'
    - '&8● &#b7afa3Multiplier: <gradient:#FF9A29:#FFCF00>%multiplier%</gradient>'
    - '&8● &#b7afa3Length: <gradient:#FF9A29:#FFCF00>%length%</gradient>'

# if you want to override the format section in the guis, you can do it here!
override-lore:
  my-boosters: []
  admin-viewer: []
  active-boosters: []

```

### Expected behaviour

Should give more money boost

### Steps to reproduce

https://i.imgur.com/OgqkG9h.gif

### Which plugin is this issue with?

axboosters

### Versions

![Image](https://github.com/user-attachments/assets/b30c3eb7-1bb6-4833-87d6-2b8955178260)
